/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import Classes.Product;
import Classes.ProductManager;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author buddh
 */

public class Cashier extends javax.swing.JFrame {

    /**
     * Creates new form Cashier
     */
    private final ProductManager productManager;

    public Cashier() {
        initComponents();
        productManager = new ProductManager();
        setupEventListeners();
        setupTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void setupEventListeners() {
        // Add action listener for delete button
        cashierdeletebtn.addActionListener((java.awt.event.ActionEvent evt) -> {
            cashierdeletebtnActionPerformed(evt);
        });

        // Add action listener for view button
        cashierptviewbtn1.addActionListener((java.awt.event.ActionEvent evt) -> {
            cashierptviewbtnActionPerformed(evt);
        });

        // Add key listener for search box
        chashiersearchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cashiersearchboxKeyReleased(evt);
            }
        });

        
    }

    private void setupTable() {
        // Set up the table model
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"ID", "Name", "Price", "Quantity", "Category"}
        ));
        // Initial load of products
        refreshTable();
    }

    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        List<Product> products = productManager.viewProducts();
        for (Product product : products) {
            model.addRow(new Object[]{
                product.getId(),
                product.getName(),
                product.getPrice(),
                product.getQuantity(),
                product.getCategory()
            });
        }
    }

    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        chashiersearchbox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cashierptidbox = new javax.swing.JTextField();
        cashierptnamebox = new javax.swing.JTextField();
        cashierptpricebox = new javax.swing.JTextField();
        cashierptquantitybox = new javax.swing.JTextField();
        cashierptcategorybox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cashierptaddbtn = new javax.swing.JButton();
        cashierdeletebtn = new javax.swing.JButton();
        cashierptviewbtn1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        cashierexitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(950, 31));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome Cashier");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 178, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 50));

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));
        jPanel3.setMinimumSize(new java.awt.Dimension(300, 490));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 490));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(270, 60));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(chashiersearchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 260, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Search");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, -1));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(270, 360));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Pet Supply");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));
        jPanel5.add(cashierptidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 140, -1));
        jPanel5.add(cashierptnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 140, -1));
        jPanel5.add(cashierptpricebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 140, -1));
        jPanel5.add(cashierptquantitybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, -1));

        cashierptcategorybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Toy", "Harnes", "Cage", "Grooming Products", "Collars", "Foods" }));
        jPanel5.add(cashierptcategorybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 140, -1));

        jLabel3.setText("ID");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, -1));

        jLabel4.setText("Name");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel5.setText("Price");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 60, -1));

        jLabel6.setText("Quantity");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 70, -1));

        jLabel7.setText("Category");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, -1));

        cashierptaddbtn.setText("Add");
        cashierptaddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierptaddbtnActionPerformed(evt);
            }
        });
        jPanel5.add(cashierptaddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        cashierdeletebtn.setText("Delete");
        jPanel5.add(cashierdeletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        cashierptviewbtn1.setText("View");
        jPanel5.add(cashierptviewbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 330));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 360, 430));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Pet Supply Details");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price", "Quantity", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 420, 290));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 440, 340));

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setPreferredSize(new java.awt.Dimension(950, 58));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Algerian", 2, 14)); // NOI18N
        jLabel8.setText("The Paws Shop");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));
        jPanel8.setPreferredSize(new java.awt.Dimension(590, 200));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashierexitbtn.setText("Exit");
        cashierexitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierexitbtnActionPerformed(evt);
            }
        });
        jPanel8.add(cashierexitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 440, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 520));

        setSize(new java.awt.Dimension(814, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    

    private void cashierexitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierexitbtnActionPerformed
        // Log the exit action
        writeToLog("Exit", "", "", "", "", "");
        System.exit(0);
    }//GEN-LAST:event_cashierexitbtnActionPerformed

    private void cashierptaddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierptaddbtnActionPerformed
        try {
            int id = Integer.parseInt(cashierptidbox.getText());
            String name = cashierptnamebox.getText();
            double price = Double.parseDouble(cashierptpricebox.getText());
            int quantity = Integer.parseInt(cashierptquantitybox.getText());
            String category = cashierptcategorybox.getSelectedItem().toString();

            Product product = new Product(id, name, price, quantity, category);
            productManager.addProduct(product);
            JOptionPane.showMessageDialog(this, "Product added successfully.");
            clearInputFields();

            // Refresh table after adding a product
            refreshTable();
            // Log the add action
            writeToLog("Add", String.valueOf(id), name, String.valueOf(price), String.valueOf(quantity), category);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter correct values.");
        }
    }//GEN-LAST:event_cashierptaddbtnActionPerformed
    
    // View products action
    private void cashierptviewbtnActionPerformed(java.awt.event.ActionEvent evt) {
        // Get the selected row index
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            // Populate the text fields with the selected row data
            cashierptidbox.setText(jTable1.getValueAt(selectedRow, 0).toString());
            cashierptnamebox.setText(jTable1.getValueAt(selectedRow, 1).toString());
            cashierptpricebox.setText(jTable1.getValueAt(selectedRow, 2).toString());
            cashierptquantitybox.setText(jTable1.getValueAt(selectedRow, 3).toString());
            cashierptcategorybox.setSelectedItem(jTable1.getValueAt(selectedRow, 4).toString());
        } else {
            // Show an error message if no row is selected
            JOptionPane.showMessageDialog(this, "Please select a product to view.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Delete product action
    private void cashierdeletebtnActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow != -1) {
                int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
                String name = jTable1.getValueAt(selectedRow, 1).toString();
                String price = jTable1.getValueAt(selectedRow, 2).toString();
                String quantity = jTable1.getValueAt(selectedRow, 3).toString();
                String category = jTable1.getValueAt(selectedRow, 4).toString();

                int confirm = JOptionPane.showConfirmDialog(this, 
                    "Are you sure you want to delete this product?",
                    "Confirm Delete",
                    JOptionPane.YES_NO_OPTION);
                
                if (confirm == JOptionPane.YES_OPTION) {
                    productManager.deleteProduct(id);
                    JOptionPane.showMessageDialog(this, "Product deleted successfully");
                    clearInputFields();
                    refreshTable();
                    // Log the delete action
                    writeToLog("Delete", String.valueOf(id), name, price, quantity, category);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a product to delete");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error deleting product: " + e.getMessage());
        }
    }

    // Search products action
    private void cashiersearchboxKeyReleased(java.awt.event.KeyEvent evt) {
        String searchText = chashiersearchbox.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        List<Product> products = productManager.viewProducts();
        for (Product product : products) {
            if (product.getName().toLowerCase().contains(searchText) ||
                product.getCategory().toLowerCase().contains(searchText) ||
                String.valueOf(product.getId()).contains(searchText)) {
                
                model.addRow(new Object[]{
                    product.getId(),
                    product.getName(),
                    product.getPrice(),
                    product.getQuantity(),
                    product.getCategory()
                });
            }
        }
    }
    
    
    
    // Update table with product list
    private void updateTable(List<Product> products) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Product product : products) {
            model.addRow(new Object[]{
                product.getId(),
                product.getName(),
                product.getPrice(),
                product.getQuantity(),
                product.getCategory()
            });
        }
    }

    
    
    // Clear input fields after adding a product
    private void clearInputFields() {
        cashierptidbox.setText("");
        cashierptnamebox.setText("");
        cashierptpricebox.setText("");
        cashierptquantitybox.setText("");
        cashierptcategorybox.setSelectedIndex(0); // Reset to default selection
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Cashier().setVisible(true);
            }
        });
    }
    // Method to write actions to cashier_actions.txt
    private void writeToLog(String action, String id, String name, String price, String quantity, String category) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("cashier_actions.txt", true))) {
            if("Exit".equals(action)){
                writer.write("Action: " + action + ", Cashier has left. ");
                writer.newLine();
            } else{
                writer.write("Action: " + action + ", ID: " + id + ", Name: " + name + ", Price: " + price + 
                             ", Quantity: " + quantity + ", Category: " + category);
                writer.newLine();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error logging action: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cashierdeletebtn;
    private javax.swing.JButton cashierexitbtn;
    private javax.swing.JButton cashierptaddbtn;
    private javax.swing.JComboBox<String> cashierptcategorybox;
    private javax.swing.JTextField cashierptidbox;
    private javax.swing.JTextField cashierptnamebox;
    private javax.swing.JTextField cashierptpricebox;
    private javax.swing.JTextField cashierptquantitybox;
    private javax.swing.JButton cashierptviewbtn1;
    private javax.swing.JTextField chashiersearchbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}