/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import Classes.Cashiers;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author buddh
 */
public class Manager_Cashier extends javax.swing.JFrame {

    
    private final ArrayList<Cashiers> cashiers;

    /**
     * Creates new form Manager_Cashier
     */
    public Manager_Cashier() {
        initComponents();
        cashiers = new ArrayList<>();
        initActions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        managercashiersearchbox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        managercashieridbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        managercashierunamebox = new javax.swing.JTextField();
        managercashieraddbtn = new javax.swing.JButton();
        managercashierviewbtn = new javax.swing.JButton();
        managercashierdeletebtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        managercashierdetailsarea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        managercashierexitbtn = new javax.swing.JButton();
        managercashiernextbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(952, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 58));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 2, 14)); // NOI18N
        jLabel1.setText("The Paws Shop");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 163, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(952, 31));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome Manager");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 50));

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(managercashiersearchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 22, 248, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Search");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 60));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cashier");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 35, 63, -1));

        jLabel4.setText("ID");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 50, -1));
        jPanel5.add(managercashieridbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 220, -1));

        jLabel5.setText("User Name");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        managercashierunamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managercashierunameboxActionPerformed(evt);
            }
        });
        jPanel5.add(managercashierunamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 220, -1));

        managercashieraddbtn.setText("Add");
        jPanel5.add(managercashieraddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        managercashierviewbtn.setText("View");
        jPanel5.add(managercashierviewbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        managercashierdeletebtn.setText("Delete");
        managercashierdeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managercashierdeletebtnActionPerformed(evt);
            }
        });
        jPanel5.add(managercashierdeletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 300));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 360, 430));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managercashierdetailsarea.setBackground(new java.awt.Color(255, 255, 204));
        managercashierdetailsarea.setColumns(20);
        managercashierdetailsarea.setRows(5);
        jScrollPane1.setViewportView(managercashierdetailsarea);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, 240));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Cashier Details");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 440, 300));

        managercashierexitbtn.setText("Exit");
        managercashierexitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managercashierexitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(managercashierexitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, -1, -1));

        managercashiernextbtn.setText("Next");
        managercashiernextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managercashiernextbtnActionPerformed(evt);
            }
        });
        getContentPane().add(managercashiernextbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        setSize(new java.awt.Dimension(814, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void managercashierunameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managercashierunameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managercashierunameboxActionPerformed

    private void managercashierexitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managercashierexitbtnActionPerformed
        // Log action
        logManagerAction("Manager has left");
        System.exit(0);
    }//GEN-LAST:event_managercashierexitbtnActionPerformed

    private void managercashiernextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managercashiernextbtnActionPerformed
        Manager_PetSupply mpt = new Manager_PetSupply();
        mpt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_managercashiernextbtnActionPerformed

    private void managercashierdeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managercashierdeletebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managercashierdeletebtnActionPerformed

    // add listners
    private void initActions() {
        managercashieraddbtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addCashier();
            }
        });

        managercashierviewbtn.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
                populateCashierInputFields();
            }
        });

        managercashierdeletebtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteCashier();
            }
        });

        // Add a search listener for the search functionality
        managercashiersearchbox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                searchCashier();
            }
        });
    }

    private void addCashier() {
        String id = managercashieridbox.getText();
        String username = managercashierunamebox.getText();

        if (id.isEmpty() || username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID and Username cannot be empty.");
            return;
        }

        Cashiers newCashier = new Cashiers(id, username);
        cashiers.add(newCashier);
        JOptionPane.showMessageDialog(this, "Cashier added successfully!");

        // Log action
        logManagerAction("Added cashier - ID: " + id + ", Username: " + username);
        
        clearInputFields();
        viewCashiers(); // Refresh the cashier details area after adding a cashier
    }

    private void searchCashier() {
        String searchQuery = managercashiersearchbox.getText().trim();

        if (searchQuery.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an ID or Username to search.");
            return;
        }

        boolean found = false;
        for (Cashiers cashier : cashiers) {
            if (cashier.getId().equals(searchQuery) || cashier.getUsername().equalsIgnoreCase(searchQuery)) {
                // Populate the input fields if cashier is found
                managercashieridbox.setText(cashier.getId());
                managercashierunamebox.setText(cashier.getUsername());
                found = true;
                break;
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, "Cashier not found.");
        }
    }

   private void populateCashierInputFields() {
        String searchQuery = managercashiersearchbox.getText().trim();

        if (searchQuery.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an ID or Username to search.");
            return;
        }

        boolean found = false;
        for (Cashiers cashier : cashiers) {
            if (cashier.getId().equals(searchQuery) || cashier.getUsername().equalsIgnoreCase(searchQuery)) {
                // Populate the input fields if cashier is found
                managercashieridbox.setText(cashier.getId());
                managercashierunamebox.setText(cashier.getUsername());
                found = true;
                break;
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, "Cashier not found.");
        }
    }

    // View button action method
    private void viewCashiers() {
        StringBuilder details = new StringBuilder();
        for (Cashiers cashier : cashiers) {
            details.append("ID: ").append(cashier.getId())
                   .append(", Username: ").append(cashier.getUsername())
                   .append("\n");
        }
        managercashierdetailsarea.setText(details.toString());
    }

    private void deleteCashier() {
        String id = managercashieridbox.getText();
        String name = managercashierunamebox.getText();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a valid ID to delete.");
            return;
        }

        Cashiers toRemove = null;
        for (Cashiers cashier : cashiers) {
            if (cashier.getId().equals(id)) {
                toRemove = cashier;
                break;
            }
        }

        if (toRemove != null) {
            cashiers.remove(toRemove);
            JOptionPane.showMessageDialog(this, "Cashier deleted successfully!");
            // Log action
            logManagerAction("Deleted cashier - ID: " + id+ ", Username: " + name);
            clearInputFields();
            viewCashiers();
        } else {
            JOptionPane.showMessageDialog(this, "Cashier not found.");
        }
    }
    
    private void clearInputFields() {
        managercashieridbox.setText("");
        managercashierunamebox.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Manager_Cashier().setVisible(true);
            }
        });
    }

    private void logManagerAction(String action) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("manager_actions.txt", true))) {
            writer.write(action);
            writer.newLine();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error logging action: " + e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton managercashieraddbtn;
    private javax.swing.JButton managercashierdeletebtn;
    private javax.swing.JTextArea managercashierdetailsarea;
    private javax.swing.JButton managercashierexitbtn;
    private javax.swing.JTextField managercashieridbox;
    private javax.swing.JButton managercashiernextbtn;
    private javax.swing.JTextField managercashiersearchbox;
    private javax.swing.JTextField managercashierunamebox;
    private javax.swing.JButton managercashierviewbtn;
    // End of variables declaration//GEN-END:variables
}
