/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author buddh
 */

public class Manager_PetSupply extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    private DefaultTableModel tableModel;

    public Manager_PetSupply() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        managerptsearchbox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        psidbox = new javax.swing.JTextField();
        psnamebox = new javax.swing.JTextField();
        pspricebox = new javax.swing.JTextField();
        psquantitybox = new javax.swing.JTextField();
        pscategorycombobox = new javax.swing.JComboBox<>();
        addpetsupplybtn = new javax.swing.JButton();
        viewpetsupplybtn = new javax.swing.JButton();
        deletepetsupplybtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        backpetsupplybtn = new javax.swing.JButton();
        exitpetsupplybtn = new javax.swing.JButton();
        logoutpetsupplybtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(952, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(952, 31));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome Manager");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 210, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 50));

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(managerptsearchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 237, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Search");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, 60));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 37, -1));

        jLabel3.setText("Name");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 37, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Pet Supply");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel5.setText("Price");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 37, -1));

        jLabel6.setText("Quantity");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 57, -1));

        jLabel7.setText("Category");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 61, -1));

        psidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psidboxActionPerformed(evt);
            }
        });
        jPanel5.add(psidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, -1));
        jPanel5.add(psnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 170, -1));
        jPanel5.add(pspricebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 170, -1));
        jPanel5.add(psquantitybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 170, -1));

        pscategorycombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Toy", "Harnes", "Cage", "Grooming Products", "Collars", "Foods" }));
        jPanel5.add(pscategorycombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 133, -1));

        addpetsupplybtn.setText("Add");
        jPanel5.add(addpetsupplybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 70, -1));

        viewpetsupplybtn.setText("View");
        jPanel5.add(viewpetsupplybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 70, -1));

        deletepetsupplybtn.setText("Delete");
        jPanel5.add(deletepetsupplybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 70, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 330));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 360, 430));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Pet Supply Details");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price", "Quantity", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 440, 240));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 440, 300));

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setPreferredSize(new java.awt.Dimension(950, 58));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Algerian", 2, 14)); // NOI18N
        jLabel8.setText("The Paws Shop");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        backpetsupplybtn.setText("Back");
        jPanel1.add(backpetsupplybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));

        exitpetsupplybtn.setText("Exit");
        exitpetsupplybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitpetsupplybtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitpetsupplybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, -1, -1));

        logoutpetsupplybtn.setText("Logout");
        jPanel1.add(logoutpetsupplybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 520));

        setSize(new java.awt.Dimension(814, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void psidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psidboxActionPerformed
         
    }//GEN-LAST:event_psidboxActionPerformed

    private void exitpetsupplybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitpetsupplybtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitpetsupplybtnActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_PetSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_PetSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_PetSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_PetSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Manager_PetSupply().setVisible(true);
            }
        });
    }
    
    // Custom initialization method to add functionality
    private boolean isTableInitialized = false;
    // Custom initialization method to add functionality
    private void initCustomComponents() {
        // Initialize the table model
        tableModel = (DefaultTableModel) jTable1.getModel();

        // Add action listeners for buttons
        addpetsupplybtn.addActionListener(evt -> addPetSupply());
        deletepetsupplybtn.addActionListener(evt -> deletePetSupply());
        backpetsupplybtn.addActionListener(evt -> goBack());
        exitpetsupplybtn.addActionListener(evt -> exitApplication());
        logoutpetsupplybtn.addActionListener(evt -> logout());

        // Add key listener for search box
        managerptsearchbox.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
              if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                searchPetSupply(managerptsearchbox.getText());
              }   
            }
        });

        // Adding Action Listener to View Button
        viewpetsupplybtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                viewSelectedPetSupply();
            }
        });
    }
    private void searchPetSupply(String query) {
        
        boolean found = false;
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            String id = String.valueOf(tableModel.getValueAt(i, 0));
            String name = String.valueOf(tableModel.getValueAt(i, 1));

            if (id.equalsIgnoreCase(query) || name.equalsIgnoreCase(query)) {
                psidbox.setText(id);
                psnamebox.setText(name);
                pspricebox.setText(String.valueOf(tableModel.getValueAt(i, 2)));
                psquantitybox.setText(String.valueOf(tableModel.getValueAt(i, 3)));
                pscategorycombobox.setSelectedItem(tableModel.getValueAt(i, 4).toString());
                found = true;
                break;
            }
        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "No matching pet supply found.");
        }
    }

    private void viewSelectedPetSupply() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            psidbox.setText(String.valueOf(tableModel.getValueAt(selectedRow, 0)));
            psnamebox.setText(String.valueOf(tableModel.getValueAt(selectedRow, 1)));
            pspricebox.setText(String.valueOf(tableModel.getValueAt(selectedRow, 2)));
            psquantitybox.setText(String.valueOf(tableModel.getValueAt(selectedRow, 3)));
            pscategorycombobox.setSelectedItem(tableModel.getValueAt(selectedRow, 4));
        } else {
            JOptionPane.showMessageDialog(this, "Please select a pet supply to view.");
        }
    }

    private void addPetSupply() {
        
        if (!isTableInitialized) {
            
            tableModel.setRowCount(0);
            isTableInitialized = true; // Set the flag to true after clearing
        }
        int id = Integer.parseInt(psidbox.getText());
        String name = psnamebox.getText();
        double price = Double.parseDouble(pspricebox.getText());
        int quantity = Integer.parseInt(psquantitybox.getText());
        String category = (String) pscategorycombobox.getSelectedItem();

        // Add new row to table
        tableModel.addRow(new Object[]{id, name, price, quantity, category});
        // Log action
        writeToLog("Add", String.valueOf(id), name, String.valueOf(price), String.valueOf(quantity), category);

        // Clear input fields
        clearInputFields();
    }

    private void viewPetSupplies() {
        
        JOptionPane.showMessageDialog(this, "View Pet Supplies feature to be implemented.");
    }

    private void deletePetSupply() {
        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow != -1) {
            String id = String.valueOf(tableModel.getValueAt(selectedRow, 0));
            String name = String.valueOf(tableModel.getValueAt(selectedRow, 1));
            String price = String.valueOf(tableModel.getValueAt(selectedRow, 2));
            String quantity = String.valueOf(tableModel.getValueAt(selectedRow, 3));
            String category = String.valueOf(tableModel.getValueAt(selectedRow, 4));
            
            tableModel.removeRow(selectedRow);
            // log
            writeToLog("Delete", String.valueOf(id), name, String.valueOf(price), String.valueOf(quantity), category);
            JOptionPane.showMessageDialog(this, "Pet supply is deleted.");
        } else {
            JOptionPane.showMessageDialog(this, "Please select a pet supply to delete.");
        }
    }

    private void goBack() {
        new Manager_Cashier().setVisible(true);
        this.dispose();
    }

    private void exitApplication() {
        writeToLog("Exit", "", "", "", "", "");
        System.exit(0);
    }

    private void logout() {
        int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?");
        if (confirmation == JOptionPane.YES_OPTION) {
            // Close this screen and show the login screen
            new Login().setVisible(true);
            this.dispose();
            writeToLog("Logout", "", "", "", "", "");

        }
    }

    private void clearInputFields() {
        psidbox.setText("");
        psnamebox.setText("");
        pspricebox.setText("");
        psquantitybox.setText("");
        pscategorycombobox.setSelectedIndex(0);
    }
    
    // Method to write actions to cashier_actions.txt
    private void writeToLog(String action, String id, String name, String price, String quantity, String category) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("manager_actions.txt", true))) {
            if("Exit".equals(action)){
                writer.write("Action: " + action + ", Manager has left. ");
                writer.newLine();
            } else if("Logout".equals(action)) {
                writer.write("Action: " + action + ", Manager has Logout. ");
                writer.newLine();
            } else{
                writer.write("Action: " + action + ", ID: " + id + ", Name: " + name + ", Price: " + price + 
                             ", Quantity: " + quantity + ", Category: " + category);
                writer.newLine();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error logging action: " + e.getMessage());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpetsupplybtn;
    private javax.swing.JButton backpetsupplybtn;
    private javax.swing.JButton deletepetsupplybtn;
    private javax.swing.JButton exitpetsupplybtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutpetsupplybtn;
    private javax.swing.JTextField managerptsearchbox;
    private javax.swing.JComboBox<String> pscategorycombobox;
    private javax.swing.JTextField psidbox;
    private javax.swing.JTextField psnamebox;
    private javax.swing.JTextField pspricebox;
    private javax.swing.JTextField psquantitybox;
    private javax.swing.JButton viewpetsupplybtn;
    // End of variables declaration//GEN-END:variables
}
